AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless E-Commerce with Event-Driven Architecture - TODOS Lambdas COM Datadog

# ============================================================================
# PARAMETERS
# ============================================================================
Parameters:
  DatadogApiKey:
    Type: String
    Description: Datadog API Key (stored in Secrets Manager)
    NoEcho: true
    Default: '{{resolve:secretsmanager:datadog:SecretString:api_key}}'

# ============================================================================
# GLOBALS - Aplicado para TODAS as funções Lambda
# ============================================================================
Globals:
  Function:
    Timeout: 30
    Runtime: python3.11
    MemorySize: 1024
    
    # ✅ Datadog Lambda Layers (aplicado globalmente)
    # IMPORTANTE: Ajuste para sua região se não for us-east-1
    Layers:
      - arn:aws:lambda:us-east-1:464622532012:layer:Datadog-Python311:95
      - arn:aws:lambda:us-east-1:464622532012:layer:Datadog-Extension:58
    
    Environment:
      Variables:
        PRODUCTS_TABLE: !Ref ProductsTable
        ORDERS_TABLE: !Ref OrdersTable
        POWERTOOLS_SERVICE_NAME: ecommerce
        LOG_LEVEL: INFO
        
        # ✅ Datadog Environment Variables (globais)
        DD_API_KEY: !Ref DatadogApiKey
        DD_SITE: datadoghq.com
        DD_ENV: prod
        DD_VERSION: '1.0.0'
        # DD_SERVICE será sobrescrito em cada função

# ============================================================================
# RESOURCES
# ============================================================================
Resources:
  # --------------------------------------------------------------------------
  # DynamoDB Tables
  # --------------------------------------------------------------------------
  ProductsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ecommerce-products
      BillingMode: PAY_PER_REQUEST
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      AttributeDefinitions:
        - AttributeName: product_id
          AttributeType: S
      KeySchema:
        - AttributeName: product_id
          KeyType: HASH

  OrdersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ecommerce-orders
      BillingMode: PAY_PER_REQUEST
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      AttributeDefinitions:
        - AttributeName: order_id
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: N
        - AttributeName: customer_id
          AttributeType: S
      KeySchema:
        - AttributeName: order_id
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: CustomerIndex
          KeySchema:
            - AttributeName: customer_id
              KeyType: HASH
            - AttributeName: timestamp
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  # --------------------------------------------------------------------------
  # SNS Topics
  # --------------------------------------------------------------------------
  OrderEventsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: ecommerce-order-events
      DisplayName: Order Events Topic

  PaymentEventsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: ecommerce-payment-events
      DisplayName: Payment Events Topic

  # --------------------------------------------------------------------------
  # SQS Queues
  # --------------------------------------------------------------------------
  InventoryQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ecommerce-inventory-queue
      VisibilityTimeout: 180
      MessageRetentionPeriod: 1209600
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt InventoryDLQ.Arn
        maxReceiveCount: 3

  InventoryDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ecommerce-inventory-dlq
      MessageRetentionPeriod: 1209600

  EmailQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ecommerce-email-queue
      VisibilityTimeout: 60
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt EmailDLQ.Arn
        maxReceiveCount: 3

  EmailDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ecommerce-email-dlq

  FraudQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ecommerce-fraud-queue
      VisibilityTimeout: 120

  # --------------------------------------------------------------------------
  # SNS Subscriptions
  # --------------------------------------------------------------------------
  EmailQueueSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: sqs
      TopicArn: !Ref OrderEventsTopic
      Endpoint: !GetAtt EmailQueue.Arn
      FilterPolicy:
        event_type:
          - order_confirmed
          - order_shipped

  FraudQueueSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: sqs
      TopicArn: !Ref PaymentEventsTopic
      Endpoint: !GetAtt FraudQueue.Arn
      RawMessageDelivery: true

  # --------------------------------------------------------------------------
  # SQS Policies
  # --------------------------------------------------------------------------
  EmailQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref EmailQueue
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: sns.amazonaws.com
            Action: sqs:SendMessage
            Resource: !GetAtt EmailQueue.Arn
            Condition:
              ArnEquals:
                aws:SourceArn: !Ref OrderEventsTopic

  FraudQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref FraudQueue
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: sns.amazonaws.com
            Action: sqs:SendMessage
            Resource: !GetAtt FraudQueue.Arn
            Condition:
              ArnEquals:
                aws:SourceArn: !Ref PaymentEventsTopic

  # --------------------------------------------------------------------------
  # API Gateway
  # --------------------------------------------------------------------------
  EcommerceApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowOrigins:
          - "*"
        AllowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
        AllowHeaders:
          - "*"

  # ==========================================================================
  # LAMBDA FUNCTIONS - TODAS INSTRUMENTADAS COM DATADOG
  # ==========================================================================

  # --------------------------------------------------------------------------
  # 1. Products Function
  # --------------------------------------------------------------------------
  ProductsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/products/
      Handler: handler.lambda_handler
      Description: Product catalog API
      Environment:
        Variables:
          DD_SERVICE: ecommerce-products
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref ProductsTable
      Events:
        ListProducts:
          Type: HttpApi
          Properties:
            Path: /products
            Method: GET
            ApiId: !Ref EcommerceApi
        GetProduct:
          Type: HttpApi
          Properties:
            Path: /products/{product_id}
            Method: GET
            ApiId: !Ref EcommerceApi

  # --------------------------------------------------------------------------
  # 2. Orders Function (PROBLEMÁTICA - Cold Start + Payment Timeout)
  # --------------------------------------------------------------------------
  OrdersFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/orders/
      Handler: handler.lambda_handler
      Description: Order processing with payment
      # ⚠️ Configurações que expõem o problema
      Timeout: 5          # Baixo para expor timeout
      MemorySize: 128     # Baixo para forçar cold starts frequentes
      Environment:
        Variables:
          DD_SERVICE: ecommerce-orders
          INVENTORY_QUEUE_URL: !GetAtt InventoryQueue.QueueUrl
          ORDER_EVENTS_TOPIC_ARN: !Ref OrderEventsTopic
          PAYMENT_EVENTS_TOPIC_ARN: !Ref PaymentEventsTopic
          PAYMENT_API_URL: https://httpbin.org/delay/6  # 6 segundos = timeout!
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref OrdersTable
        - DynamoDBReadPolicy:
            TableName: !Ref ProductsTable
        - SQSSendMessagePolicy:
            QueueName: !GetAtt InventoryQueue.QueueName
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt OrderEventsTopic.TopicName
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt PaymentEventsTopic.TopicName
      Events:
        CreateOrder:
          Type: HttpApi
          Properties:
            Path: /orders
            Method: POST
            ApiId: !Ref EcommerceApi
        GetOrders:
          Type: HttpApi
          Properties:
            Path: /orders
            Method: GET
            ApiId: !Ref EcommerceApi

  # --------------------------------------------------------------------------
  # 3. Inventory Function
  # --------------------------------------------------------------------------
  InventoryFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/inventory/
      Handler: handler.lambda_handler
      Description: Async inventory management
      ReservedConcurrentExecutions: 5
      Environment:
        Variables:
          DD_SERVICE: ecommerce-inventory
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ProductsTable
      Events:
        InventoryQueue:
          Type: SQS
          Properties:
            Queue: !GetAtt InventoryQueue.Arn
            BatchSize: 10
            MaximumBatchingWindowInSeconds: 5

  # --------------------------------------------------------------------------
  # 4. Email Function
  # --------------------------------------------------------------------------
  EmailFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/email/
      Handler: handler.lambda_handler
      Description: Email notifications
      Timeout: 30
      Environment:
        Variables:
          DD_SERVICE: ecommerce-email
          FROM_EMAIL: noreply@ecommerce-demo.com
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref OrdersTable
      Events:
        EmailQueue:
          Type: SQS
          Properties:
            Queue: !GetAtt EmailQueue.Arn
            BatchSize: 10

  # --------------------------------------------------------------------------
  # 5. Analytics Function
  # --------------------------------------------------------------------------
  AnalyticsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/analytics/
      Handler: handler.lambda_handler
      Description: Order analytics processing
      Environment:
        Variables:
          DD_SERVICE: ecommerce-analytics
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref OrdersTable
      Events:
        OrderCreated:
          Type: SNS
          Properties:
            Topic: !Ref OrderEventsTopic
            FilterPolicy:
              event_type:
                - order_created

  # --------------------------------------------------------------------------
  # 6. Fraud Detection Function
  # --------------------------------------------------------------------------
  FraudFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/fraud/
      Handler: handler.lambda_handler
      Description: Fraud detection and risk analysis
      Timeout: 120
      MemorySize: 2048
      Environment:
        Variables:
          DD_SERVICE: ecommerce-fraud
          RISK_THRESHOLD: "0.7"
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref OrdersTable
      Events:
        FraudQueue:
          Type: SQS
          Properties:
            Queue: !GetAtt FraudQueue.Arn
            BatchSize: 5

  # --------------------------------------------------------------------------
  # 7. DynamoDB Stream Processor Function
  # --------------------------------------------------------------------------
  OrderStreamFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/stream_processor/
      Handler: handler.lambda_handler
      Description: Process DynamoDB Stream events
      Environment:
        Variables:
          DD_SERVICE: ecommerce-stream-processor
      Policies:
        - DynamoDBStreamReadPolicy:
            TableName: !Ref OrdersTable
            StreamName: !GetAtt OrdersTable.StreamArn
      Events:
        Stream:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt OrdersTable.StreamArn
            StartingPosition: TRIM_HORIZON
            BatchSize: 100
            MaximumBatchingWindowInSeconds: 10

# ============================================================================
# OUTPUTS
# ============================================================================
Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${EcommerceApi}.execute-api.${AWS::Region}.amazonaws.com"
    Export:
      Name: !Sub "${AWS::StackName}-ApiEndpoint"
  
  OrderEventsTopicArn:
    Description: Order Events SNS Topic ARN
    Value: !Ref OrderEventsTopic
    Export:
      Name: !Sub "${AWS::StackName}-OrderEventsTopic"
  
  InventoryQueueUrl:
    Description: Inventory Queue URL
    Value: !GetAtt InventoryQueue.QueueUrl
    Export:
      Name: !Sub "${AWS::StackName}-InventoryQueue"
  
  ProductsTableName:
    Description: Products DynamoDB Table Name
    Value: !Ref ProductsTable
    Export:
      Name: !Sub "${AWS::StackName}-ProductsTable"
  
  OrdersTableName:
    Description: Orders DynamoDB Table Name
    Value: !Ref OrdersTable
    Export:
      Name: !Sub "${AWS::StackName}-OrdersTable"